In [1]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

if os.environ.get('RUNTIME_ENV_LOCATION_TYPE') == 'external':
    endpoint_4ee44b67c1364daa8980c509a11a2582 = 'https://s3.us.cloud-object-storage.appdomain.cloud'
else:
    endpoint_4ee44b67c1364daa8980c509a11a2582 = 'https://s3.private.us.cloud-object-storage.appdomain.cloud'

client_4ee44b67c1364daa8980c509a11a2582 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='S74cX5nyL6zNO5GxQpfeG3AxM1bWDAOE7PYaIPBZUY6Y',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url=endpoint_4ee44b67c1364daa8980c509a11a2582)

body = client_4ee44b67c1364daa8980c509a11a2582.get_object(Bucket='croprecommendation-donotdelete-pr-pkrqpmzos7ngct',Key='cp_final.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body)
df.head()


State_Name District_Name  Crop_Year       Season    Crop  \
0  Andaman and Nicobar Islands      NICOBARS       2000  Kharif         rice   
1  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year   banana   
2  Andaman and Nicobar Islands      NICOBARS       2001  Kharif         rice   
3  Andaman and Nicobar Islands      NICOBARS       2002  Kharif         rice   
4  Andaman and Nicobar Islands      NICOBARS       2002  Whole Year   banana   

    Area  Production  
0  102.0      321.00  
1  176.0      641.00  
2   83.0      300.00  
3  189.2      510.84  
4  213.0     1278.00

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35204 entries, 0 to 35203
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   State_Name     35204 non-null  object 
 1   District_Name  35204 non-null  object 
 2   Crop_Year      35204 non-null  int64  
 3   Season         35204 non-null  object 
 4   Crop           35204 non-null  object 
 5   Area           35204 non-null  float64
 6   Production     34882 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 1.9+ MB


In [3]:
df.isnull().any()

State_Name       False
District_Name    False
Crop_Year        False
Season           False
Crop             False
Area             False
Production        True
dtype: bool

In [4]:
(df[df['Production'] == 0]['Crop']).value_counts()

mango     114
papaya     71
maize      64
orange     34
banana     29
grapes     19
apple       4
rice        4
Name: Crop, dtype: int64

In [5]:
df['Crop'].value_counts()

rice         15104
maize        13947
banana        3209
jute          1453
papaya         483
mango          449
orange         271
grapes         129
blackgram      118
lentil          31
coffee           6
apple            4
Name: Crop, dtype: int64

In [6]:
df.dropna(inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34882 entries, 0 to 35203
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   State_Name     34882 non-null  object 
 1   District_Name  34882 non-null  object 
 2   Crop_Year      34882 non-null  int64  
 3   Season         34882 non-null  object 
 4   Crop           34882 non-null  object 
 5   Area           34882 non-null  float64
 6   Production     34882 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 2.1+ MB


In [8]:
df.drop(['Crop_Year'], axis= 1, inplace=True)

In [9]:
df

State_Name District_Name       Season    Crop  \
0      Andaman and Nicobar Islands      NICOBARS  Kharif         rice   
1      Andaman and Nicobar Islands      NICOBARS  Whole Year   banana   
2      Andaman and Nicobar Islands      NICOBARS  Kharif         rice   
3      Andaman and Nicobar Islands      NICOBARS  Kharif         rice   
4      Andaman and Nicobar Islands      NICOBARS  Whole Year   banana   
...                            ...           ...          ...     ...   
35199                  West Bengal       PURULIA  Autumn        maize   
35200                  West Bengal       PURULIA  Autumn         rice   
35201                  West Bengal       PURULIA  Summer        maize   
35202                  West Bengal       PURULIA  Summer         rice   
35203                  West Bengal       PURULIA  Winter         rice   

           Area  Production  
0         102.0      321.00  
1         176.0      641.00  
2          83.0      300.00  
3         189.2      510.84  
4         213.0     1278.00  
...         ...         ...  
35199    6317.0    13337.00  
35200     264.0      721.00  
35201     325.0     2039.00  
35202     306.0      801.00  
35203  279151.0   597899.00  

[34882 rows x 6 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34882 entries, 0 to 35203
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   State_Name     34882 non-null  object 
 1   District_Name  34882 non-null  object 
 2   Season         34882 non-null  object 
 3   Crop           34882 non-null  object 
 4   Area           34882 non-null  float64
 5   Production     34882 non-null  float64
dtypes: float64(2), object(4)
memory usage: 1.9+ MB


In [11]:
df.columns

Index(['State_Name', 'District_Name', 'Season', 'Crop', 'Area', 'Production'], dtype='object')

In [12]:
features = ['State_Name', 'District_Name', 'Season', 'Crop', 'Area']
X = df[features]
y = df[['Production']]

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

In [14]:
print(X_train.shape)
print(X_test.shape)

(29649, 5)
(5233, 5)


In [15]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()
le4 = LabelEncoder()
X_train['State_Name'] = le1.fit_transform(X_train['State_Name'])
X_train['District_Name'] = le2.fit_transform(X_train['District_Name'])
X_train['Season'] = le3.fit_transform(X_train['Season'])
X_train['Crop'] = le4.fit_transform(X_train['Crop'])

<ipython-input-15-ae6a775c959d>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['State_Name'] = le1.fit_transform(X_train['State_Name'])
<ipython-input-15-ae6a775c959d>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['District_Name'] = le2.fit_transform(X_train['District_Name'])
<ipython-input-15-ae6a775c959d>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documen

In [16]:
X_train

State_Name  District_Name  Season  Crop     Area
7031            4            400       1     5    144.0
9856            6            572       1     7   9209.0
29718          30            121       1     7     16.0
8271            4            514       2     7   6309.0
20142          18            110       4    10    315.0
...           ...            ...     ...   ...      ...
17057          16            235       4     8    266.0
6266            4            301       3     7   9050.0
11459          11            282       1    11  37272.0
860             1            562       4    10      8.0
15983          15            434       3    11   8143.0

[29649 rows x 5 columns]

In [17]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
scaler_y= StandardScaler()
scaler_x.fit(X_train)
X_train = scaler_x.transform(X_train)
X_train = pd.DataFrame(X_train)

In [18]:
X_train

0         1         2         3         4
0     -1.223905  0.478809 -0.677384 -1.035241 -0.491275
1     -1.028663  1.413463 -0.677384 -0.377872 -0.315494
2      1.314246 -1.037288 -0.677384 -0.377872 -0.493757
3     -1.223905  1.098289  0.016212 -0.377872 -0.371728
4      0.142792 -1.097062  1.403402  0.608181 -0.487959
...         ...       ...       ...       ...       ...
29644 -0.052451 -0.417808  1.403402 -0.049188 -0.488910
29645 -1.223905 -0.059161  0.709807 -0.377872 -0.318577
29646 -0.540557 -0.162408 -0.677384  0.936865  0.228682
29647 -1.516769  1.359123  1.403402  0.608181 -0.493912
29648 -0.150072  0.663566  0.709807  0.936865 -0.336165

[29649 rows x 5 columns]

In [19]:
scaler_y.fit(y_train)
y_train = pd.DataFrame(scaler_y.transform(y_train))
y_train

0
0     -0.420615
1     -0.304450
2     -0.429188
3     -0.299106
4     -0.417567
...         ...
29644 -0.429316
29645 -0.322625
29646 -0.005788
29647 -0.424442
29648 -0.271290

[29649 rows x 1 columns]

In [20]:
from sklearn.ensemble import RandomForestRegressor
reg = RandomForestRegressor(random_state=0)
reg.fit(X_train, y_train)

<ipython-input-20-6a9041bc66bc>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  reg.fit(X_train, y_train)


RandomForestRegressor(random_state=0)

In [21]:
X_test['State_Name'] = le1.transform(X_test['State_Name'])
X_test['District_Name'] = le2.transform(X_test['District_Name'])
X_test['Season'] = le3.transform(X_test['Season'])
X_test['Crop'] = le4.transform(X_test['Crop'])

<ipython-input-21-1625233fee9a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['State_Name'] = le1.transform(X_test['State_Name'])
<ipython-input-21-1625233fee9a>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['District_Name'] = le2.transform(X_test['District_Name'])
<ipython-input-21-1625233fee9a>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http

In [22]:
X_test = pd.DataFrame(scaler_x.transform(X_test))
y_pred = reg.predict(X_test)

In [23]:
y_test = pd.DataFrame(scaler_y.transform(y_test))

In [24]:
y_pred = pd.DataFrame(y_pred)
y_pred

0
0    -0.429290
1    -0.101300
2     0.009342
3    -0.370476
4     0.088118
...        ...
5228 -0.424555
5229 -0.271912
5230 -0.393089
5231  0.139308
5232  0.775014

[5233 rows x 1 columns]

In [25]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
print("MAE = ", mae)
print("MSE = ", mse)

MAE =  0.08771166842679079
MSE =  0.08405920202847585


In [26]:
import numpy as np
print("RMSE = ", np.sqrt(mse))
print("R2 = ", r2_score(y_test, y_pred))

RMSE =  0.2899296501368493
R2 =  0.9107029992287151


In [27]:
list(X_test.iloc[15])

[-0.7357990246281644,
 0.565753119023915,
 -0.6773835295420583,
 0.9368649652992979,
 -0.22452964544849574]

In [28]:
t = reg.predict([[-0.742451332458198,
 0.5579899763275868,
 -0.6734988864532463,
 0.9277322733931527,
 -0.22584441728883164]])

In [31]:
scaler_y.inverse_transform(t)

array([14187.3])

In [32]:
scaler_x.var_

array([1.04932882e+02, 3.38652891e+04, 2.07868064e+00, 9.25639984e+00,
       2.65943690e+09])

In [35]:
scaler_x.mean_

array([1.65372862e+01, 3.11887146e+02, 1.97662653e+00, 8.14965092e+00,
       2.54789329e+04])

In [36]:
scaler_x.scale_

array([1.02436752e+01, 1.84025240e+02, 1.44176303e+00, 3.04243321e+00,
       5.15697285e+04])

In [37]:
scaler_y.var_

array([2.21843763e+10])

In [38]:
scaler_y.mean_

array([63944.11448649])

In [39]:
scaler_y.scale_

array([148944.2053662])

In [ ]:
from ibm_watson_machine_learning import APIClient

In [ ]:
wml_credential={
    "url":"https://us-south.ml.cloud.ibm.com",
    "apikey":"McsFLx4OecKVAiAYsOpudQUJJHbYWO22f3WMAAiBdd5k"
}
client=APIClient(wml_credential)

In [ ]:
def guid_from_space_name(client,space_name):
    space=client.spaces.get_details()
#     print(space)
    return(next(item for item in space['resources'] if item['entity']["name"]==space_name)['metadata']['id'])


In [ ]:
space_uid=guid_from_space_name(client,'models')
print("Space UID = "+space_uid)

In [ ]:
space_uid

In [ ]:
client.set.default_space(space_uid)

In [ ]:
client.software_specifications.list()

In [ ]:
software_spec_uid=client.software_specifications.get_uid_by_name('default_py3.8')
software_spec_uid

In [ ]:
model_details=client.repository.store_model(model=reg,meta_props={
    client.repository.ModelMetaNames.NAME:"crop_reco",
    client.repository.ModelMetaNames.TYPE:"scikit-learn_0.23",
    client.repository.ModelMetaNames.SOFTWARE_SPEC_UID:software_spec_uid
})

In [ ]:
model_id=client.repository.get_model_uid(model_details)

In [ ]:
model_id